# Generated by Django 3.2.6 on 2021-08-24 02:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='acc_hash',
            field=models.CharField(default=uuid.uuid4, max_length=35, unique=True),
        ),
    ]
